export { default as HomePage } from './HomePage/HomePage'
export { default as OrdersPage } from './OrdersPage/OrdersPage'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
export { default as ProductPage } from './ProductPage/ProductPage'
export { default as CartPage } from './CartPage/CartPage'
export { default as RegisterPage } from './RegisterPage/RegisterPage'
export { default as SigninPage } from './SigninPage/SigninPage'
export { default as ProductsPage } from './ProductsPage/ProductsPage'