export { default as HomePage } from './HomePage/HomePage'
export { default as OrdersPage } from './OrdersPage/OrdersPage'
export { default as ProfilePage } from './ProfilePage/ProfilePage'
export { default as ProductPage } from './ProductPage/ProductPage'
export { default as CartPage } from './CartPage/CartPage'